### ISSUE TITLE
[Request]: Consider and document how to integrate sandbox in other containerized applications

### ISSUE THREAD

**Issue by eike-hass** [iotaledger/iota-sandbox#24]
### Feature description

Making the sanbox play nice with other containerized applications might help developers develop and test their software more effectively.

### Motivation

We want to use the sandbox to develop the Selv application which is also orchestrated through docker-compose and traefik.  Our current solution requires to attach the Selv app to the sandbox network and access hornet via service name + port. There might other approaches like:
- Not binding the sandbox setup to a specific host
- Consider docker host networking

### Requirements

1. Consider a canonical way using sandbox in containerized applications
2. Document the approach

### Are you planning to do it yourself in a pull request?

No

**Comment by Dr-Electron** [comment]
We need to figure out if we can use Traefik without host in a rule or use host regex
